# Generated by Django 4.2 on 2023-04-11 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "primary_color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BLU", "Blue"),
                            ("BRN", "Brown"),
                            ("GLD", "Gold"),
                            ("GRN", "Green"),
                            ("ORG", "Orange"),
                            ("PNK", "Pink"),
                            ("PUR", "Purple"),
                            ("RED", "Red"),
                            ("SLV", "Silver"),
                            ("YLW", "Yellow"),
                            ("BLK", "Black"),
                            ("WHT", "White"),
                            ("GRY", "Gray"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BLU", "Blue"),
                            ("BRN", "Brown"),
                            ("GLD", "Gold"),
                            ("GRN", "Green"),
                            ("ORG", "Orange"),
                            ("PNK", "Pink"),
                            ("PUR", "Purple"),
                            ("RED", "Red"),
                            ("SLV", "Silver"),
                            ("YLW", "Yellow"),
                            ("BLK", "Black"),
                            ("WHT", "White"),
                            ("GRY", "Gray"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the car, be specific",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Heat",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("number", models.IntegerField()),
                ("completed_timestamp", models.DateTimeField(blank=True, null=True)),
                ("timer_correlation_uuid", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RaceEvent",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("position_podiums", models.IntegerField(default=4)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="race_event.raceevent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HeatResult",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("lane_number", models.IntegerField()),
                ("time_result", models.FloatField()),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="race_event.car"
                    ),
                ),
                (
                    "heat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="race_event.heat",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="heat",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="race_event.race"
            ),
        ),
        migrations.CreateModel(
            name="CarMaker",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "helper",
                    models.ForeignKey(
                        blank=True,
                        help_text="Helper for this car maker",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="helpers",
                        to="race_event.carmaker",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CarEventRegistration",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("registration_number", models.IntegerField()),
                ("checked_in", models.BooleanField(default=False)),
                ("checked_in_timestamp", models.DateTimeField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("weight_official", models.BooleanField(default=False)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="race_event.car"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="race_event.raceevent",
                    ),
                ),
                (
                    "official_signoff_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="official_signoff_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="car",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="race_event.carmaker",
            ),
        ),
    ]
