# Generated by Django 4.2 on 2023-04-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("race_event", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="race",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
