# Generated by Django 4.2 on 2023-04-19 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarMaker",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "helper",
                    models.ForeignKey(
                        blank=True,
                        help_text="Helper for this car maker",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="helpers",
                        to="race_car.carmaker",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "primary_color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BLU", "Blue"),
                            ("BRN", "Brown"),
                            ("GLD", "Gold"),
                            ("GRN", "Green"),
                            ("ORG", "Orange"),
                            ("PNK", "Pink"),
                            ("PUR", "Purple"),
                            ("RED", "Red"),
                            ("SLV", "Silver"),
                            ("YLW", "Yellow"),
                            ("BLK", "Black"),
                            ("WHT", "White"),
                            ("GRY", "Gray"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BLU", "Blue"),
                            ("BRN", "Brown"),
                            ("GLD", "Gold"),
                            ("GRN", "Green"),
                            ("ORG", "Orange"),
                            ("PNK", "Pink"),
                            ("PUR", "Purple"),
                            ("RED", "Red"),
                            ("SLV", "Silver"),
                            ("YLW", "Yellow"),
                            ("BLK", "Black"),
                            ("WHT", "White"),
                            ("GRY", "Gray"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the car, be specific",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="race_car.carmaker",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
