# Generated by Django 4.2.5 on 2024-01-13 17:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("grand_prix", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackTimerManufacturer",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GrandPrixRawDataLog",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("correlation_id", models.UUIDField()),
                ("raw_data", models.TextField()),
                ("source_ip", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grand_prix.grandprix",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackTimer",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("model", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=100)),
                ("lane_count", models.IntegerField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="track_gate_pictures"
                    ),
                ),
                (
                    "output_file",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sample_result_string",
                    models.CharField(
                        blank=True,
                        default='@A=1.758# B=1.392" C=1.086! D=0.000  E=0.000  F=0.000',
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_timers",
                        to="race_track.tracktimermanufacturer",
                    ),
                ),
            ],
            options={
                "unique_together": {("manufacturer", "model", "version")},
            },
        ),
    ]
