# Generated by Django 4.2 on 2023-04-19 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrackTimerManufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrackTimer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=100)),
                ("lane_count", models.IntegerField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="track_gate_pictures"
                    ),
                ),
                (
                    "output_file",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sample_result_string",
                    models.CharField(
                        blank=True,
                        default='@A=1.758# B=1.392" C=1.086! D=0.000  E=0.000  F=0.000',
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_timers",
                        to="race_track.tracktimermanufacturer",
                    ),
                ),
            ],
            options={
                "unique_together": {("manufacturer", "model", "version")},
            },
        ),
    ]
