# Generated by Django 4.2.5 on 2024-01-13 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("race_car", "0001_initial"),
        ("race_organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrandPrix",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="race_organization.raceorganization",
                    ),
                ),
            ],
            options={
                "unique_together": {("slug", "organization")},
            },
        ),
        migrations.CreateModel(
            name="RaceSession",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("position_podiums", models.IntegerField(default=4)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grand_prix.grandprix",
                    ),
                ),
            ],
            options={
                "unique_together": {("slug", "event")},
            },
        ),
        migrations.CreateModel(
            name="SessionHeat",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("heat_number", models.IntegerField()),
                ("completed_timestamp", models.DateTimeField(blank=True, null=True)),
                ("timer_correlation_uuid", models.UUIDField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grand_prix.racesession",
                    ),
                ),
            ],
            options={
                "unique_together": {("heat_number", "session")},
            },
        ),
        migrations.CreateModel(
            name="SessionHeatResult",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("lane_number", models.IntegerField()),
                ("time_result", models.FloatField()),
                ("correlation_id", models.TextField(blank=True, null=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="race_car.car"
                    ),
                ),
                (
                    "heat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grand_prix.sessionheat",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GrandPrixRegistration",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("registration_number", models.IntegerField()),
                ("checked_in", models.BooleanField(default=False)),
                ("checked_in_timestamp", models.DateTimeField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("weight_official", models.BooleanField(default=False)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="race_car.car"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grand_prix.grandprix",
                    ),
                ),
                (
                    "official_signoff_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="official_signoff_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GrandPrixInvitation",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Invitation code for this Grand Prix",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "lock_date",
                    models.DateField(
                        blank=True,
                        help_text="Date after which the invitation code will no longer be valid",
                        null=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Optionally set a password in addition to the invitation code",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("locked", "Locked"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=255,
                    ),
                ),
                (
                    "grandprix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grand_prix.grandprix",
                    ),
                ),
            ],
            options={
                "unique_together": {("grandprix", "code")},
            },
        ),
    ]
