# Generated by Django 4.2 on 2023-04-20 00:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("grand_prix", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sessionheat",
            unique_together={("heat_number", "session")},
        ),
        migrations.CreateModel(
            name="GrandPrixInvitation",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Invitation code for this Grand Prix",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "lock_date",
                    models.DateField(
                        blank=True,
                        help_text="Date after which the invitation code will no longer be valid",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("locked", "Locked"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=255,
                    ),
                ),
                (
                    "grandprix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grand_prix.grandprix",
                    ),
                ),
            ],
            options={
                "unique_together": {("grandprix", "code")},
            },
        ),
    ]
