# Generated by Django 4.2 on 2023-04-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("race_organization", "0001_initial"),
        ("grand_prix", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grandprix",
            name="slug",
            field=models.SlugField(default="text", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="grandprix",
            unique_together={("slug", "organization")},
        ),
    ]
